package constants

const VULNMAP_EXIT_CODE_OK = 0
const VULNMAP_EXIT_CODE_ERROR = 2
const VULNMAP_INTEGRATION_NAME = "CLI_V1_PLUGIN"
const VULNMAP_INTEGRATION_NAME_ENV = "VULNMAP_INTEGRATION_NAME"
const VULNMAP_INTEGRATION_VERSION_ENV = "VULNMAP_INTEGRATION_VERSION"
const VULNMAP_HTTPS_PROXY_ENV = "HTTPS_PROXY"
const VULNMAP_HTTP_PROXY_ENV = "HTTP_PROXY"
const VULNMAP_HTTP_NO_PROXY_ENV = "NO_PROXY"
const VULNMAP_NPM_PROXY_ENV = "NPM_CONFIG_PROXY"
const VULNMAP_NPM_HTTPS_PROXY_ENV = "NPM_CONFIG_HTTPS_PROXY"
const VULNMAP_NPM_HTTP_PROXY_ENV = "NPM_CONFIG_HTTP_PROXY"
const VULNMAP_NPM_NO_PROXY_ENV = "NPM_CONFIG_NO_PROXY"
const VULNMAP_NPM_ALL_PROXY = "ALL_PROXY"
const VULNMAP_CA_CERTIFICATE_LOCATION_ENV = "NODE_EXTRA_CA_CERTS"
const VULNMAP_INTERNAL_NO_PROXY = "localhost,127.0.0.1,::1"
const VULNMAP_OAUTH_ACCESS_TOKEN_ENV = "VULNMAP_OAUTH_TOKEN"
const VULNMAP_ANALYTICS_DISABLED_ENV = "VULNMAP_DISABLE_ANALYTICS"
const VULNMAP_INTERNAL_ORGID_ENV = "VULNMAP_INTERNAL_ORGID"
const VULNMAP_OPENSSL_CONF = "OPENSSL_CONF"

const VULNMAP_HTTPS_PROXY_ENV_SYSTEM = "VULNMAP_SYSTEM_HTTPS_PROXY"
const VULNMAP_HTTP_PROXY_ENV_SYSTEM = "VULNMAP_SYSTEM_HTTP_PROXY"
const VULNMAP_HTTP_NO_PROXY_ENV_SYSTEM = "VULNMAP_SYSTEM_NO_PROXY"
